[workspace]
resolver = "2"
members = [
	"elasti-gneiss-core",
	"elasti-gneiss-core-async",
	"elasti-gneiss-core-sync",
	"elasti-gneiss-threaded",
	"elasti-gneiss-tokio",
	"elasti-gneiss-aws-tokio",
	"gneiss-mqtt",
	"gneiss-mqtt-aws",
]